# Translation

- UUID: `82fd0cce-2b41-423f-92ad-636d0872045c`
- Event Type: `EditChapterEvent`
- Edit only the `Translation (zh_Hant)` blocks below.

## title

### Source (en)

~~~text
Re-using data
~~~

### Translation (zh_Hant)

~~~text
資料再利用
~~~

## text

### Source (en)

~~~text
Before you decide to embark on any new study, it is good practice to check all options to re-use existing available data, either collected or generated by yourself in an earlier project, or data from others (Barend Mons calls this "Other PEople's Data And Services" or OPEDAS). This can include reusable data that have been created for an earlier study, and also so-called "reference data" which is used by many projects.

It is not because we can generate massive amounts of data that we always need to do so. Creating data with public money is bringing with it the responsibility to treat those data well and (if potentially useful) make them available for re-use by others. And the circle is only complete if such data is actually re-used.
~~~

### Translation (zh_Hant)

~~~text
在您決定開始任何新研究之前，最好檢查所有現有的可用資料，作為可重複使用的選項。這些資料可能是您在早期專案中收集或產生的，也可能是來自他人的資料（Barend Mons 將其稱為「他人的資料與服務」或 OPEDAS）。這可以包括為早期研究建立的可重用資料，以及許多專案都會使用的所謂「參考資料」。

我們並非因為能夠產生海量資料就必須總是這麼做。利用公帑產出資料，也隨之帶來了妥善處理這些資料的責任，並且（若具備潛在用途）應將其提供給他人重複使用。而唯有當這些資料確實被重複使用時，這個循環才算完整。
~~~
